---
apiVersion: v1
kind: Service
metadata:
  name: satisfactory
  labels:
    app: satisfactory
spec:
  type: LoadBalancer
  ports:
  - port: 15777
    protocol: UDP
    name: "query"
    targetPort: "query"
  - port: 15000
    protocol: UDP
    name: "beacon"
    targetPort: "beacon"
  - port: 7777
    protocol: UDP
    name: "game"
    targetPort: "game"
  selector:
    app: satisfactory
